name: Deploy to FTP

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: europ.iq.pl
        username: chalupy_www
        password: ${{ secrets.keystoeko_kieszonkowe }}
        local-dir: ./
        server-dir: /www/eko.chalupy.online/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env
          converter.py
          feedpages.md
          slides_draft.md
          task.md
